const currentPage = document.body.dataset.page;

const state = {
  sidebarOpen: false,
  liveSimulation: false,
};

function initSidebarToggle() {
  const toggle = document.querySelector('.menu-toggle');
  if (!toggle) return;
  const sidebar = document.querySelector('.sidebar');
  toggle.addEventListener('click', () => {
    state.sidebarOpen = !state.sidebarOpen;
    sidebar.classList.toggle('sidebar-open', state.sidebarOpen);
  });
}

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomElement(array) {
  return array[Math.floor(Math.random() * array.length)];
}

function renderAllPages() {
  renderDashboardKPIs();
  renderDashboardBranches();
  renderDashboardAlerts();
  renderDeviceIntelligence();
  renderFraudDetection();
  renderCustomerPortal();
  renderAuditLogs();
  renderAnalyticsPage();
  renderTrackingPage();
}

async function simulateLiveTelemetry() {
  const devices = dataManager.getDevices();
  if (!devices.length) return;

  const device = getRandomElement(devices);
  const newRisk = Math.max(12, Math.min(95, device.risk_score + getRandomInt(-12, 10)));
  const syncStates = ['synced', 'desynced', 'sync-in-progress'];
  const newSync = getRandomElement(syncStates);
  const newSimChanges = device.sim_changes + (Math.random() > 0.78 ? 1 : 0);
  const newTimestamp = new Date();

  await dataManager.updateDevice(device.id, {
    risk_score: newRisk,
    erp_sync_status: newSync,
    sim_changes: newSimChanges,
    last_sim_change: newSimChanges > device.sim_changes ? 0 : device.last_sim_change,
    timestamp: newTimestamp,
  });

  renderAllPages();
}

function startLiveSimulation() {
  if (state.liveSimulation) return;
  state.liveSimulation = true;
  simulateLiveTelemetry();
  setInterval(simulateLiveTelemetry, 6500);
}

/**
 * Dashboard-specific data rendering
 */
function renderDashboardKPIs() {
  if (currentPage !== 'dashboard') return;
  const metrics = dataManager.getDashboardMetrics();
  const kpiGrid = document.getElementById('kpi-grid');
  
  const kpis = [
    {
      label: 'Active devices',
      value: metrics.activeDevices.toLocaleString(),
      trend: '+12%',
      trendClass: 'low',
      description: 'Devices currently reporting to the security intelligence layer.'
    },
    {
      label: 'Fraud alerts',
      value: metrics.fraudAlerts,
      trend: '+24%',
      trendClass: 'high',
      description: 'Alerts generated by device mismatches, suspicious activations, or ERP desynchronization.'
    },
    {
      label: 'Protected devices',
      value: metrics.protectedDevices.toLocaleString(),
      trend: '+8%',
      trendClass: 'medium',
      description: 'Devices enrolled in customer protection and insurance workflows.'
    },
    {
      label: 'ERP sync health',
      value: metrics.erpSyncHealth + '%',
      trend: 'Stable',
      trendClass: 'low',
      description: 'Real-time status for ERP inventory sync and device lifecycle updates.'
    }
  ];

  kpiGrid.innerHTML = kpis.map(kpi => `
    <article class="card kpi-card">
      <div class="metric">
        <div>
          <small>${kpi.label}</small>
          <div class="value">${kpi.value}</div>
        </div>
        <span class="badge ${kpi.trendClass}">${kpi.trend}</span>
      </div>
      <p>${kpi.description}</p>
    </article>
  `).join('');
}

function renderDashboardBranches() {
  if (currentPage !== 'dashboard') return;
  const branchesList = document.getElementById('branches-list');
  const branches = dataManager.getBranches().slice(0, 2);

  branchesList.innerHTML = branches.map(branch => `
    <div class="device-card">
      <div class="status-pill"><span></span>${branch.location} • ${branch.alerts} alerts</div>
      <div><strong>${branch.name}</strong></div>
      <p>Staff: ${branch.staff} • Devices tracked: ${branch.devices} • Active security scans</p>
    </div>
  `).join('');
}

function renderDashboardAlerts() {
  if (currentPage !== 'dashboard') return;
  const alertsList = document.getElementById('alerts-list');
  const alerts = dataManager.getFraudAlerts({ status: 'open' });

  alertsList.innerHTML = alerts.slice(0, 3).map(alert => `
    <div class="activity-item">
      <div><strong>${alert.description}</strong></div>
      <span>IMEI ${dataManager.formatIMEI(alert.device_id)} • ${alert.branch} • ${dataManager.formatDate(alert.created_at)}</span>
    </div>
  `).join('');
}

/**
 * Device Intelligence Page
 */
function renderDeviceIntelligence() {
  if (currentPage !== 'device-intelligence') return;
  
  // Render KPI grid
  const deviceKpiGrid = document.getElementById('device-kpi-grid');
  const metrics = dataManager.getDashboardMetrics();
  
  if (deviceKpiGrid) {
    const unsoldActiveDevices = dataManager.getDevices().filter(d => d.erp_status === 'unsold' && d.activation_status === 'active').length;
    const totalSimChanges = dataManager.getDevices().reduce((sum, device) => sum + (device.sim_changes || 0), 0);
    const kpis = [
      { label: 'Unsold active devices', value: unsoldActiveDevices, trend: unsoldActiveDevices > 0 ? 'Urgent' : 'Stable', class: unsoldActiveDevices > 0 ? 'high' : 'low' },
      { label: 'SIM profile changes', value: totalSimChanges, trend: 'Monitoring', class: totalSimChanges > 20 ? 'high' : 'medium' },
      { label: 'ERP sync warnings', value: metrics.erpSyncWarnings, trend: 'Stable', class: metrics.erpSyncWarnings > 0 ? 'high' : 'low' },
      { label: 'High risk score', value: metrics.highRiskDevices, trend: 'Critical', class: metrics.highRiskDevices > 3 ? 'critical' : 'medium' },
    ];
    
    deviceKpiGrid.innerHTML = `
      <div class="card-grid kpi-grid">
        ${kpis.map(kpi => `
          <article class="card kpi-card">
            <div class="metric">
              <div>
                <small>${kpi.label}</small>
                <div class="value">${kpi.value}</div>
              </div>
              <span class="badge ${kpi.class}">${kpi.trend}</span>
            </div>
            <p>Device intelligence metric for operational awareness.</p>
          </article>
        `).join('')}
      </div>
    `;
  }
  
  // Render device cards
  const deviceList = document.querySelector('.device-list');
  const devices = dataManager.getDevices().slice(0, 3);
  
  if (deviceList) {
    deviceList.innerHTML = devices.map(device => `
      <div class="device-card">
        <div class="status-pill"><span></span>IMEI ${dataManager.formatIMEI(device.imei)} • ${dataManager.getRiskLevel(device.risk_score)} risk</div>
        <div><strong>${device.model}</strong></div>
        <p>Activation: ${device.activation_status} • ERP: ${device.erp_status} • Last SIM: ${device.last_sim_change ? device.last_sim_change + 'm ago' : 'Never'}</p>
      </div>
    `).join('');
  }

  // Render device table
  const table = document.querySelector('table tbody');
  if (table) {
    table.innerHTML = dataManager.getDevices().map(device => `
      <tr>
        <td>${dataManager.formatIMEI(device.imei)}</td>
        <td>${device.model}</td>
        <td>${device.activation_status}</td>
        <td>${device.sim_changes} swap${device.sim_changes !== 1 ? 's' : ''}</td>
        <td>${device.erp_sync_status}</td>
        <td><span class="badge ${dataManager.getRiskLevel(device.risk_score)}">${dataManager.getRiskLevel(device.risk_score)}</span></td>
      </tr>
    `).join('');
  }
}

/**
 * Fraud Detection Page
 */
function renderFraudDetection() {
  if (currentPage !== 'fraud') return;
  
  // Render KPI grid
  const fraudKpiGrid = document.getElementById('fraud-kpi-grid');
  const alerts = dataManager.getFraudAlerts({ status: 'open' });
  
  if (fraudKpiGrid) {
    const metrics = {
      suspicious: dataManager.getDevices().filter(d => d.risk_score > 50).length + 46,
      anomalies: alerts.length + 120,
      cases: dataManager.data.investigations.filter(i => i.status !== 'ready-for-closure').length,
      resolved: 64,
    };
    
    const kpis = [
      { label: 'Suspicious devices', value: metrics.suspicious, trend: '24 urgent', class: 'high' },
      { label: 'Anomaly events', value: metrics.anomalies, trend: 'Critical', class: 'critical' },
      { label: 'Open cases', value: metrics.cases, trend: 'In progress', class: 'medium' },
      { label: 'Resolved issues', value: metrics.resolved, trend: 'Today', class: 'low' },
    ];
    
    fraudKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Fraud detection metric for security operations.</p>
      </article>
    `).join('');
  }
  
  const alerts_open = dataManager.getFraudAlerts({ status: 'open' });
  const alertList = document.querySelector('.alert-list');
  
  if (alertList) {
    alertList.innerHTML = alerts_open.map(alert => `
      <div class="alert-item">
        <div>
          <strong>${alert.description}</strong>
          <p>${alert.branch} • ${alert.devices_affected} device${alert.devices_affected !== 1 ? 's' : ''} matched • escalated</p>
        </div>
        <span class="badge ${alert.severity}">${alert.severity}</span>
      </div>
    `).join('');
  }

  // Render fraud table
  const tables = document.querySelectorAll('table tbody');
  if (tables.length > 1) {
    tables[1].innerHTML = dataManager.getFraudAlerts().map((alert, idx) => `
      <tr>
        <td>${alert.id.replace('alert_', '')}</td>
        <td>${alert.device_id}</td>
        <td><span class="badge ${alert.severity}">${alert.severity}</span></td>
        <td>${alert.status}</td>
        <td>${dataManager.formatDate(alert.created_at)}</td>
      </tr>
    `).join('');
  }
}

/**
 * Customer Protection Page
 */
function renderCustomerPortal() {
  if (currentPage !== 'customer') return;
  
  // Render KPI grid
  const customerKpiGrid = document.getElementById('customer-kpi-grid');
  const customers = dataManager.getCustomers();
  
  if (customerKpiGrid) {
    const kpis = [
      { label: 'Protected units', value: customers.length + 3900, trend: '+6%', class: 'medium' },
      { label: 'Theft reports', value: 24, trend: 'Ongoing', class: 'high' },
      { label: 'Recovery progress', value: '72%', trend: 'Strong', class: 'low' },
      { label: 'Warranty coverage', value: '88%', trend: 'Healthy', class: 'low' },
    ];
    
    customerKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Customer protection metric for operational awareness.</p>
      </article>
    `).join('');
  }
  
  const deviceList = document.querySelector('.device-list');
  
  if (deviceList) {
    deviceList.innerHTML = customers.slice(0, 2).map(customer => `
      <div class="device-card">
        <div class="status-pill"><span></span>Customer: ${customer.name}</div>
        <div><strong>${customer.protection_status === 'active' ? '✓ Protected' : '⚠ Under Review'}</strong></div>
        <p>Devices: ${customer.devices.length} • Recovery: ${customer.recovery_progress}% • Theft reports: ${customer.theft_reports}</p>
      </div>
    `).join('');
  }

  // Render customer table
  const custTable = document.querySelector('table tbody');
  if (custTable) {
    custTable.innerHTML = customers.map(customer => `
      <tr>
        <td>${customer.name}</td>
        <td>${customer.devices.length}</td>
        <td><span class="badge ${customer.protection_status === 'active' ? 'low' : 'medium'}">${customer.protection_status}</span></td>
        <td>${customer.protection_status === 'active' ? 'Active' : 'Pending'}</td>
        <td>${customer.recovery_progress}%</td>
      </tr>
    `).join('');
  }
}

/**
 * Audit Logs Page
 */
function renderAuditLogs() {
  if (currentPage !== 'audit-logs') return;
  
  const localWorkspace = JSON.parse(localStorage.getItem('secguard_workspace_v1') || '{"auditLogs":[]}');
  const localLogs = (localWorkspace.auditLogs || []).map(log => ({
    time: new Date(log.time),
    actor: log.actor,
    action: log.action,
    target: log.target,
    result: 'Recorded',
  }));
  const logs = [...localLogs, ...dataManager.data.audit_logs];
  const auditTable = document.querySelector('table tbody');
  
  if (auditTable) {
    auditTable.innerHTML = logs.map(log => `
      <tr>
        <td>${dataManager.formatDate(log.time).includes('ago') ? new Date().toLocaleTimeString().slice(0, 5) + ' • ' + log.time.toLocaleDateString() : log.time.toLocaleTimeString()}</td>
        <td>${log.actor}</td>
        <td>${log.action}</td>
        <td>${log.target}</td>
        <td><span class="badge low">${log.result}</span></td>
      </tr>
    `).join('');
  }
}


function initCharts() {
  if (typeof Chart === 'undefined') return;

  if (currentPage === 'dashboard') {
    const activityCtx = document.getElementById('deviceActivityChart');
    if (activityCtx) {
      new Chart(activityCtx, {
        type: 'line',
        data: {
          labels: ['00:00', '04:00', '08:00', '12:00', '16:00', '20:00', '24:00'],
          datasets: [{
            label: 'Security events',
            data: [18, 24, 31, 42, 36, 52, 48],
            borderColor: '#5b87ff',
            backgroundColor: 'rgba(91, 135, 255, 0.16)',
            tension: 0.35,
            fill: true,
            pointRadius: 0,
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: { grid: { display: false }, ticks: { color: '#8e9fd6' } },
            y: { grid: { color: 'rgba(255,255,255,0.06)' }, ticks: { color: '#8e9fd6' } }
          }
        }
      });
    }

    const fraudCtx = document.getElementById('fraudSplitChart');
    if (fraudCtx) {
      new Chart(fraudCtx, {
        type: 'doughnut',
        data: {
          labels: ['Potential Fraud', 'Verified Alerts', 'Investigations'],
          datasets: [{
            data: [32, 18, 14],
            backgroundColor: ['#ff5d8f', '#73f3e8', '#d950ff'],
            hoverOffset: 6,
          }]
        },
        options: { responsive: true, plugins: { legend: { position: 'bottom', labels: { color: '#bec8f8' } } } }
      });
    }
  }

  if (currentPage === 'analytics') {
    const trendsCtx = document.getElementById('trendChart');
    if (trendsCtx) {
      const branches = dataManager.getBranches();
      new Chart(trendsCtx, {
        type: 'bar',
        data: {
          labels: branches.map(b => b.name),
          datasets: [{
            label: 'Alert volume',
            data: branches.map(b => b.alerts),
            backgroundColor: '#5b87ff',
            borderRadius: 20,
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: { grid: { display: false }, ticks: { color: '#b2bcff' } },
            y: { grid: { color: 'rgba(255,255,255,0.06)' }, ticks: { color: '#b2bcff' } }
          }
        }
      });
    }

    const riskCtx = document.getElementById('riskChart');
    if (riskCtx) {
      new Chart(riskCtx, {
        type: 'line',
        data: {
          labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
          datasets: [{
            label: 'Risk exposure',
            data: [58, 52, 49, 61, 68, 74, 83],
            borderColor: '#73f3e8',
            backgroundColor: 'rgba(115, 243, 232, 0.16)',
            tension: 0.4,
            fill: true,
            pointRadius: 3,
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: { grid: { display: false }, ticks: { color: '#b2bcff' } },
            y: { grid: { color: 'rgba(255,255,255,0.06)' }, ticks: { color: '#b2bcff' } }
          }
        }
      });
    }
  }
}

function initNotifications() {
  const items = document.querySelectorAll('.alert-item');
  items.forEach((item, index) => {
    item.style.animation = `fadeUp 0.48s ease ${(index * 0.05)}s both`;
  });
}

function initLoginForm() {
  const form = document.querySelector('.login-form');
  if (!form) return;
  let selectedRole = localStorage.getItem('secguard_active_role') || 'company_admin';

  document.querySelectorAll('[data-role-login]').forEach(button => {
    button.classList.toggle('active', button.dataset.roleLogin === selectedRole);
    button.addEventListener('click', () => {
      selectedRole = button.dataset.roleLogin;
      localStorage.setItem('secguard_active_role', selectedRole);
      document.querySelectorAll('[data-role-login]').forEach(item => item.classList.remove('active'));
      button.classList.add('active');
    });
  });

  form.addEventListener('submit', event => {
    event.preventDefault();
    const email = form.querySelector('input[type="email"]').value;
    const password = form.querySelector('input[type="password"]').value;
    if (!email || !password) {
      alert('Please provide email and password.');
      return;
    }
    if (window.SecguardSupabase) {
      window.SecguardSupabase.login(email, password, selectedRole).then(({ error, local }) => {
        if (error && !local) {
          alert(error.message || 'Supabase login failed. Use Sign up workspace user first if this account is new.');
          return;
        }
        window.location.href = window.SecguardSupabase.routeForRole(selectedRole);
      });
      return;
    }
    window.location.href = 'dashboard.html';
  });

  const signupButton = document.querySelector('[data-signup]');
  if (signupButton) {
    signupButton.addEventListener('click', () => {
      const email = form.querySelector('input[type="email"]').value;
      const password = form.querySelector('input[type="password"]').value;
      if (!email || !password) {
        alert('Enter email and password before signup.');
        return;
      }
      if (!window.SecguardSupabase) {
        alert('Supabase is not loaded.');
        return;
      }
      window.SecguardSupabase.signup(email, password, selectedRole).then(({ error }) => {
        if (error) {
          alert(error.message || 'Signup failed.');
          return;
        }
        alert('Signup request sent. Check email confirmation if Supabase requires it.');
      });
    });
  }

  const googleButton = document.querySelector('[data-google-login]');
  if (googleButton) {
    googleButton.addEventListener('click', () => {
      if (!window.SecguardSupabase) {
        alert('Supabase is not loaded.');
        return;
      }
      window.SecguardSupabase.googleLogin(selectedRole);
    });
  }
}

function initDeviceForm() {
  if (currentPage !== 'device-intelligence') return;
  const deviceForm = document.getElementById('device-input-form');
  if (!deviceForm) return;

  deviceForm.addEventListener('submit', event => {
    event.preventDefault();

    const imei = document.getElementById('imei-input').value.trim();
    const model = document.getElementById('model-input').value.trim();
    const status = document.getElementById('status-input').value.trim();
    const risk = document.getElementById('risk-input').value;

    if (!imei || !model || !status) {
      alert('Please complete all required fields.');
      return;
    }

    const riskScore = risk === 'high' ? 84 : risk === 'medium' ? 58 : 24;

    dataManager.addDevice({
      imei,
      model,
      activation_status: status,
      sim_changes: 0,
      last_sim_change: 0,
      erp_status: 'Synced',
      erp_sync_status: 'Synced',
      risk_score: riskScore,
      assigned_branch: 'Field Office',
      last_seen: 'Just now',
      battery_health: 'Good',
      network_load: 'Normal',
      service_tier: 'Enterprise',
      active: true,
    }).then(() => {
      renderDeviceIntelligence();
      deviceForm.reset();
      alert('Mock device added successfully.');
    });
  });
}

function initActiveNav() {
  const links = document.querySelectorAll('nav a');
  links.forEach(link => {
    const href = link.getAttribute('href');
    if (href && location.pathname.endsWith(href)) {
      link.classList.add('active');
    }
  });
}

function getTrackingSignalStrength(score) {
  if (score >= 90) return 5;
  if (score >= 70) return 4;
  if (score >= 50) return 3;
  if (score >= 30) return 2;
  return 1;
}

function renderTrackingPage() {
  if (currentPage !== 'tracking') return;
  
  const trackingKpiGrid = document.getElementById('tracking-kpi-grid');
  const deviceList = document.querySelector('.device-list');
  const trackingTableBody = document.getElementById('tracking-table-body');

  const devices = dataManager.getDevices().map(device => {
    const signalStrength = getTrackingSignalStrength(device.risk_score);
    const routeStatus = device.erp_sync_status !== 'synced'
      ? 'ERP mismatch'
      : device.risk_score > 80
      ? 'Off route'
      : 'On route';

    return {
      ...device,
      signalStrength,
      signalLabel: '▮'.repeat(signalStrength) + '▯'.repeat(5 - signalStrength),
      lastSeenLabel: dataManager.formatDate(device.timestamp),
      routeStatus,
    };
  });

  const liveDevices = devices.filter(device => device.activation_status === 'active');
  const desyncedDevices = devices.filter(device => device.erp_sync_status !== 'synced');
  const offRouteDevices = devices.filter(device => device.routeStatus !== 'On route');
  const averageSignal = devices.length
    ? Math.round(devices.reduce((sum, device) => sum + device.signalStrength, 0) / devices.length)
    : 0;

  if (trackingKpiGrid) {
    const kpis = [
      {
        label: 'Live devices',
        value: liveDevices.length,
        trend: 'Real-time',
        class: 'low',
      },
      {
        label: 'ERP desyncs',
        value: desyncedDevices.length,
        trend: 'Action',
        class: desyncedDevices.length > 0 ? 'high' : 'low',
      },
      {
        label: 'Off-route alerts',
        value: offRouteDevices.length,
        trend: 'Monitoring',
        class: offRouteDevices.length > 0 ? 'high' : 'low',
      },
      {
        label: 'Avg signal',
        value: `${averageSignal}/5`,
        trend: 'Healthy',
        class: averageSignal > 3 ? 'low' : 'medium',
      },
    ];
    
    trackingKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Live tracking performance metric for the field feed.</p>
      </article>
    `).join('');
  }

  if (deviceList) {
    const topDevices = devices
      .sort((a, b) => b.timestamp - a.timestamp)
      .slice(0, 3);

    deviceList.innerHTML = topDevices.map(device => `
      <div class="device-card">
        <div class="status-pill ${device.routeStatus === 'On route' ? 'low' : device.routeStatus === 'ERP mismatch' ? 'high' : 'medium'}">
          <span></span>${dataManager.formatIMEI(device.imei)}
        </div>
        <div><strong>${device.model}</strong></div>
        <p>Last online: ${device.lastSeenLabel} • Signal: ${device.signalStrength} bars • ${device.routeStatus}</p>
      </div>
    `).join('');
  }

  const mapSummary = document.getElementById('tracking-map-summary');
  if (mapSummary) {
    mapSummary.textContent = `${liveDevices.length} live devices • ${desyncedDevices.length} ERP desyncs • ${offRouteDevices.length} off-route alerts`; 
  }

  const trackingOffRoutePill = document.getElementById('tracking-offroute-pill');
  if (trackingOffRoutePill) {
    trackingOffRoutePill.innerHTML = `<strong>${offRouteDevices.length}</strong> devices off-route`;
  }

  if (trackingTableBody) {
    trackingTableBody.innerHTML = devices.map(device => `
      <tr>
        <td>${dataManager.formatIMEI(device.imei)}<br><small>${device.model}</small></td>
        <td>${device.lastSeenLabel}</td>
        <td>${device.routeStatus}</td>
        <td>${device.signalLabel}</td>
        <td>${device.erp_sync_status}</td>
      </tr>
    `).join('');
  }
}

function initTrackingRefresh() {
  if (currentPage !== 'tracking') return;
  const refreshBtn = document.querySelector('.page-header .btn');
  if (!refreshBtn) return;

  refreshBtn.addEventListener('click', () => {
    renderTrackingPage();
    refreshBtn.textContent = 'Feed refreshed';
    setTimeout(() => {
      refreshBtn.textContent = 'Refresh feed';
    }, 1200);
  });
}

function renderAnalyticsPage() {
  if (currentPage !== 'analytics') return;
  
  const analyticsKpiGrid = document.querySelector('.kpi-grid');
  
  if (analyticsKpiGrid) {
    const kpis = [
      { label: 'Alert coverage', value: '82%', trend: 'Wide', class: 'low' },
      { label: 'Risk index', value: '68', trend: 'Medium', class: 'medium' },
      { label: 'Branch anomalies', value: '13', trend: 'Elevated', class: 'high' },
      { label: 'Investigation velocity', value: '1.9d', trend: 'Fast', class: 'low' },
    ];
    
    analyticsKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Analytics metric for operational insight.</p>
      </article>
    `).join('');
  }
}

async function initPage() {
  initSidebarToggle();
  initLoginForm();

  if (typeof dataManager === 'undefined') return;

  initCharts();
  initNotifications();
  initDeviceForm();
  initTrackingRefresh();
  initActiveNav();

  await dataManager.load();

  // Render page-specific data
  renderDashboardKPIs();
  renderDashboardBranches();
  renderDashboardAlerts();
  renderDeviceIntelligence();
  renderFraudDetection();
  renderCustomerPortal();
  renderAuditLogs();
  renderAnalyticsPage();
  renderTrackingPage();

  startLiveSimulation();
}

window.addEventListener('DOMContentLoaded', initPage);
