const currentPage = document.body.dataset.page;

const state = {
  sidebarOpen: false,
  liveSimulation: false,
  trackingMap: null,
  trackingMarkers: [],
};

function getActiveRole() {
  return window.SecguardAuth?.getRole() || 'company_admin';
}

function enforceRoleAccess() {
  if (currentPage === 'login') return true;
  return window.SecguardAuth ? SecguardAuth.enforce() : true;
}

function applyRoleNavigation() {
  if (currentPage === 'login') return;
  if (!window.SecguardAuth) return;
  const allowed = SecguardAuth.allowedPages();
  document.querySelectorAll('.nav-group a').forEach(link => {
    const href = link.getAttribute('href');
    if (href && !allowed.includes(href)) link.remove();
  });
}

function initSidebarToggle() {
  const toggle = document.querySelector('.menu-toggle');
  if (!toggle) return;
  const sidebar = document.querySelector('.sidebar');
  toggle.addEventListener('click', () => {
    state.sidebarOpen = !state.sidebarOpen;
    sidebar.classList.toggle('sidebar-open', state.sidebarOpen);
  });
}

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomElement(array) {
  return array[Math.floor(Math.random() * array.length)];
}

function getVisibleDevices() {
  const devices = dataManager.getDevices();
  if (getActiveRole() !== 'customer') return devices;
  return devices.filter(device => device.customer_owned);
}

function showToast(message) {
  let stack = document.querySelector('.toast-stack');
  if (!stack) {
    stack = document.createElement('div');
    stack.className = 'toast-stack';
    document.body.appendChild(stack);
  }
  const toast = document.createElement('div');
  toast.className = 'toast';
  toast.textContent = message;
  stack.appendChild(toast);
  setTimeout(() => toast.remove(), 3600);
}

function showFatalError(error) {
  console.error(error);
  const shell = document.querySelector('.main-shell') || document.body;
  const panel = document.createElement('div');
  panel.className = 'card';
  panel.style.margin = '22px';
  panel.innerHTML = `
    <div class="top-bar"><div><small>System error</small><strong>Secguard could not render this view</strong></div></div>
    <p>${error?.message || 'An unexpected error occurred while loading this workspace.'}</p>
  `;
  shell.prepend(panel);
}

function getVisibleCustomers() {
  const customers = dataManager.getCustomers();
  if (getActiveRole() !== 'customer') return customers;
  const ownedDeviceIds = new Set(getVisibleDevices().map(device => device.id));
  return customers.filter(customer => (customer.devices || []).some(id => ownedDeviceIds.has(id)));
}

function renderAllPages() {
  renderDashboardKPIs();
  renderDashboardBranches();
  renderDashboardAlerts();
  renderDeviceIntelligence();
  renderFraudDetection();
  renderCustomerPortal();
  renderAuditLogs();
  renderAnalyticsPage();
  renderTrackingPage();
}

async function simulateLiveTelemetry() {
  const devices = dataManager.getDevices();
  if (!devices.length) return;

  const device = getRandomElement(devices);
  const newRisk = Math.max(12, Math.min(95, device.risk_score + getRandomInt(-12, 10)));
  const syncStates = ['synced', 'desynced', 'sync-in-progress'];
  const newSync = getRandomElement(syncStates);
  const newSimChanges = device.sim_changes + (Math.random() > 0.78 ? 1 : 0);
  const newTimestamp = new Date();

  await dataManager.updateDevice(device.id, {
    risk_score: newRisk,
    erp_sync_status: newSync,
    sim_changes: newSimChanges,
    last_sim_change: newSimChanges > device.sim_changes ? 0 : device.last_sim_change,
    timestamp: newTimestamp,
  });

  if (newSync === 'desynced' || newRisk > 80) {
    showToast(`Security event: ${device.model} risk changed to ${newRisk}.`);
  }

  renderAllPages();
}

function startLiveSimulation() {
  if (state.liveSimulation) return;
  if (!['dashboard', 'device-intelligence', 'fraud', 'tracking', 'customer', 'analytics'].includes(currentPage)) return;
  state.liveSimulation = true;
  simulateLiveTelemetry();
  setInterval(simulateLiveTelemetry, 6500);
}

/**
 * Dashboard-specific data rendering
 */
function renderDashboardKPIs() {
  if (currentPage !== 'dashboard') return;
  const metrics = dataManager.getDashboardMetrics();
  const kpiGrid = document.getElementById('kpi-grid');
  
  const kpis = [
    {
      label: 'Active devices',
      value: metrics.activeDevices.toLocaleString(),
      trend: '+12%',
      trendClass: 'low',
      description: 'Devices currently reporting to the security intelligence layer.'
    },
    {
      label: 'Fraud alerts',
      value: metrics.fraudAlerts,
      trend: '+24%',
      trendClass: 'high',
      description: 'Alerts generated by device mismatches, suspicious activations, or ERP desynchronization.'
    },
    {
      label: 'Protected devices',
      value: metrics.protectedDevices.toLocaleString(),
      trend: '+8%',
      trendClass: 'medium',
      description: 'Devices enrolled in customer protection and insurance workflows.'
    },
    {
      label: 'ERP sync health',
      value: metrics.erpSyncHealth + '%',
      trend: 'Stable',
      trendClass: 'low',
      description: 'Real-time status for ERP inventory sync and device lifecycle updates.'
    }
  ];

  kpiGrid.innerHTML = kpis.map(kpi => `
    <article class="card kpi-card">
      <div class="metric">
        <div>
          <small>${kpi.label}</small>
          <div class="value">${kpi.value}</div>
        </div>
        <span class="badge ${kpi.trendClass}">${kpi.trend}</span>
      </div>
      <p>${kpi.description}</p>
    </article>
  `).join('');
}

function renderDashboardBranches() {
  if (currentPage !== 'dashboard') return;
  const branchesList = document.getElementById('branches-list');
  if (!branchesList) return;
  const branches = dataManager.getBranches().slice(0, 2);

  branchesList.innerHTML = branches.map(branch => `
    <div class="device-card">
      <div class="status-pill"><span></span>${branch.location} &bull; ${branch.alerts} alerts</div>
      <div><strong>${branch.name}</strong></div>
      <p>Staff: ${branch.staff} &bull; Devices tracked: ${branch.devices} &bull; Active security scans</p>
    </div>
  `).join('');
}

function renderDashboardAlerts() {
  if (currentPage !== 'dashboard') return;
  const alertsList = document.getElementById('alerts-list');
  if (!alertsList) return;
  const alerts = dataManager.getFraudAlerts({ status: 'open' });

  alertsList.innerHTML = alerts.slice(0, 3).map(alert => `
    <div class="activity-item">
      <div><strong>${alert.description}</strong></div>
      <span>Device ${alert.device_id} &bull; ${alert.branch} &bull; ${dataManager.formatDate(alert.created_at)}</span>
    </div>
  `).join('');
}

/**
 * Device Intelligence Page
 */
function renderDeviceIntelligence() {
  if (currentPage !== 'device-intelligence') return;
  
  // Render KPI grid
  const deviceKpiGrid = document.getElementById('device-kpi-grid');
  const metrics = dataManager.getDashboardMetrics();
  
  if (deviceKpiGrid) {
    const unsoldActiveDevices = dataManager.getDevices().filter(d => d.erp_status === 'unsold' && d.activation_status === 'active').length;
    const totalSimChanges = dataManager.getDevices().reduce((sum, device) => sum + (device.sim_changes || 0), 0);
    const kpis = [
      { label: 'Unsold active devices', value: unsoldActiveDevices, trend: unsoldActiveDevices > 0 ? 'Urgent' : 'Stable', class: unsoldActiveDevices > 0 ? 'high' : 'low' },
      { label: 'SIM profile changes', value: totalSimChanges, trend: 'Monitoring', class: totalSimChanges > 20 ? 'high' : 'medium' },
      { label: 'ERP sync warnings', value: metrics.erpSyncWarnings, trend: 'Stable', class: metrics.erpSyncWarnings > 0 ? 'high' : 'low' },
      { label: 'High risk score', value: metrics.highRiskDevices, trend: 'Critical', class: metrics.highRiskDevices > 3 ? 'critical' : 'medium' },
    ];
    
    deviceKpiGrid.innerHTML = `
      <div class="card-grid kpi-grid">
        ${kpis.map(kpi => `
          <article class="card kpi-card">
            <div class="metric">
              <div>
                <small>${kpi.label}</small>
                <div class="value">${kpi.value}</div>
              </div>
              <span class="badge ${kpi.class}">${kpi.trend}</span>
            </div>
            <p>Device intelligence metric for operational awareness.</p>
          </article>
        `).join('')}
      </div>
    `;
  }
  
  // Render device cards
  const deviceList = document.querySelector('.device-list');
  const devices = dataManager.getDevices().slice(0, 3);
  
  if (deviceList) {
    deviceList.innerHTML = devices.map(device => `
      <div class="device-card">
        <div class="status-pill"><span></span>IMEI ${dataManager.formatIMEI(device.imei)} &bull; ${dataManager.getRiskLevel(device.risk_score)} risk</div>
        <div><strong>${device.model}</strong></div>
        <p>Activation: ${device.activation_status} &bull; ERP: ${device.erp_status} &bull; Last SIM: ${device.last_sim_change ? device.last_sim_change + 'm ago' : 'Never'}</p>
      </div>
    `).join('');
  }

  // Render device table
  const table = document.querySelector('table tbody');
  if (table) {
    table.innerHTML = dataManager.getDevices().map(device => `
      <tr>
        <td>${dataManager.formatIMEI(device.imei)}</td>
        <td>${device.model}</td>
        <td>${device.activation_status}</td>
        <td>${device.sim_changes} swap${device.sim_changes !== 1 ? 's' : ''}</td>
        <td>${device.erp_sync_status}</td>
        <td><span class="badge ${dataManager.getRiskLevel(device.risk_score)}">${dataManager.getRiskLevel(device.risk_score)}</span></td>
      </tr>
    `).join('');
  }

  const activityList = document.querySelector('.activity-list');
  if (activityList) {
    activityList.innerHTML = dataManager.getDevices().slice(0, 3).map(device => `
      <div class="activity-item">
        <div><strong>${device.activation_status === 'active' ? 'Device activity detected' : 'Device awaiting activation'}</strong></div>
        <span>${dataManager.formatIMEI(device.imei)} &bull; ERP ${device.erp_status} &bull; Risk ${device.risk_score}</span>
      </div>
    `).join('');
  }
}

/**
 * Fraud Detection Page
 */
function renderFraudDetection() {
  if (currentPage !== 'fraud') return;
  
  // Render KPI grid
  const fraudKpiGrid = document.getElementById('fraud-kpi-grid');
  const alerts = dataManager.getFraudAlerts({ status: 'open' });
  
  if (fraudKpiGrid) {
    const metrics = {
      suspicious: dataManager.getDevices().filter(d => d.risk_score > 50).length,
      anomalies: alerts.length,
      cases: dataManager.data.investigations.filter(i => i.status !== 'ready-for-closure').length,
      resolved: dataManager.getFraudAlerts().filter(alert => alert.status !== 'open').length,
    };
    
    const kpis = [
      { label: 'Suspicious devices', value: metrics.suspicious, trend: metrics.suspicious ? 'Review' : 'Clear', class: metrics.suspicious ? 'high' : 'low' },
      { label: 'Anomaly events', value: metrics.anomalies, trend: metrics.anomalies ? 'Active' : 'Clear', class: metrics.anomalies ? 'critical' : 'low' },
      { label: 'Open cases', value: metrics.cases, trend: 'In progress', class: 'medium' },
      { label: 'Resolved issues', value: metrics.resolved, trend: 'Reviewed', class: 'low' },
    ];
    
    fraudKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Fraud detection metric for security operations.</p>
      </article>
    `).join('');
  }
  
  const alerts_open = dataManager.getFraudAlerts({ status: 'open' });
  const alertList = document.querySelector('.alert-list');
  
  if (alertList) {
    alertList.innerHTML = alerts_open.map(alert => `
      <div class="alert-item">
        <div>
          <strong>${alert.description}</strong>
          <p>${alert.branch} &bull; ${alert.devices_affected} device${alert.devices_affected !== 1 ? 's' : ''} matched &bull; escalated</p>
        </div>
        <span class="badge ${alert.severity}">${alert.severity}</span>
      </div>
    `).join('');
  }

  // Render fraud table
  const tables = document.querySelectorAll('table tbody');
  if (tables.length) {
    tables[tables.length - 1].innerHTML = dataManager.getFraudAlerts().map(alert => `
      <tr>
        <td>${alert.id.replace('alert_', '')}</td>
        <td>${alert.device_id}</td>
        <td><span class="badge ${alert.severity}">${alert.severity}</span></td>
        <td>${alert.status}</td>
        <td>${dataManager.formatDate(alert.created_at)}</td>
      </tr>
    `).join('');
  }

  const activityList = document.querySelector('.activity-list');
  if (activityList) {
    activityList.innerHTML = dataManager.data.investigations.map(item => `
      <div class="activity-item">
        <div><strong>Case #${item.case_number} - ${item.type}</strong></div>
        <span>Analyst: ${item.analyst} &bull; ${item.status} &bull; ${dataManager.formatDate(item.updated_at)}</span>
      </div>
    `).join('');
  }
}

/**
 * Customer Protection Page
 */
function renderCustomerPortal() {
  if (currentPage !== 'customer') return;
  
  // Render KPI grid
  const customerKpiGrid = document.getElementById('customer-kpi-grid');
  const customers = getVisibleCustomers();
  
  if (customerKpiGrid) {
    const theftReports = customers.reduce((sum, customer) => sum + Number(customer.theft_reports || 0), 0);
    const avgRecovery = customers.length
      ? Math.round(customers.reduce((sum, customer) => sum + Number(customer.recovery_progress || 0), 0) / customers.length)
      : 0;
    const warrantyCoverage = customers.length
      ? Math.round((customers.filter(customer => customer.protection_status === 'active').length / customers.length) * 100)
      : 0;
    const kpis = [
      { label: 'Protected units', value: customers.filter(customer => customer.protection_status === 'active').length, trend: 'Live', class: 'medium' },
      { label: 'Theft reports', value: theftReports, trend: theftReports ? 'Ongoing' : 'Clear', class: theftReports ? 'high' : 'low' },
      { label: 'Recovery progress', value: `${avgRecovery}%`, trend: 'Average', class: avgRecovery > 70 ? 'low' : 'medium' },
      { label: 'Warranty coverage', value: `${warrantyCoverage}%`, trend: 'Protected', class: warrantyCoverage > 75 ? 'low' : 'medium' },
    ];
    
    customerKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Customer protection metric for operational awareness.</p>
      </article>
    `).join('');
  }
  
  const deviceList = document.querySelector('.device-list');
  
  if (deviceList) {
    deviceList.innerHTML = customers.length ? customers.slice(0, 2).map(customer => `
      ${(() => {
        const device = dataManager.getDevice((customer.devices || [])[0]);
        return `
      <div class="device-card">
        <div class="status-pill"><span></span>${device ? dataManager.formatIMEI(device.imei) : 'No IMEI yet'}</div>
        <div><strong>${customer.protection_status === 'active' ? 'Protected' : 'Under Review'}</strong></div>
        <p>${customer.name} &bull; ${device ? device.model : 'Device pending'} &bull; Recovery: ${customer.recovery_progress}% &bull; Theft reports: ${customer.theft_reports}</p>
      </div>
        `;
      })()}
    `).join('') : '<div class="activity-item"><strong>No customer device yet</strong><span>Use the form above to register or report your phone.</span></div>';
  }

  // Render customer table
  const custTable = document.querySelector('table tbody');
  if (custTable) {
    custTable.innerHTML = customers.length ? customers.map(customer => `
      ${(() => {
        const device = dataManager.getDevice((customer.devices || [])[0]);
        return `
      <tr>
        <td>${customer.name}</td>
        <td>${device ? dataManager.formatIMEI(device.imei) : 'Pending'}</td>
        <td><span class="badge ${customer.protection_status === 'active' ? 'low' : 'medium'}">${customer.protection_status}</span></td>
        <td>${device ? device.warranty || 'Review' : 'Pending'}</td>
        <td>${customer.recovery_progress}%</td>
      </tr>
        `;
      })()}
    `).join('') : '<tr><td colspan="5">No customer records yet. Register or report a phone above.</td></tr>';
  }

  const activityList = document.querySelector('.activity-list');
  if (activityList) {
    activityList.innerHTML = customers.length ? customers.slice(0, 4).map(customer => {
      const device = dataManager.getDevice((customer.devices || [])[0]);
      return `
        <div class="activity-item">
          <div><strong>${customer.theft_reports ? 'Recovery workflow active' : 'Protection record active'}</strong></div>
          <span>${customer.name} &bull; ${device ? dataManager.formatIMEI(device.imei) : 'Pending IMEI'} &bull; ${customer.recovery_progress}% complete</span>
        </div>
      `;
    }).join('') : '<div class="activity-item"><strong>No recovery timeline yet</strong><span>Register or report a phone to start the workflow.</span></div>';
  }
}

/**
 * Audit Logs Page
 */
function renderAuditLogs() {
  if (currentPage !== 'audit-logs') return;
  let localWorkspace = { auditLogs: [] };
  try {
    localWorkspace = JSON.parse(localStorage.getItem('secguard_workspace_v1') || '{"auditLogs":[]}');
  } catch (error) {
    console.warn('Workspace audit logs could not be read.', error);
  }
  const localLogs = (localWorkspace.auditLogs || []).map(log => ({
    time: new Date(log.time),
    actor: log.actor,
    action: log.action,
    target: log.target,
    result: 'Recorded',
  }));
  const logs = [...localLogs, ...dataManager.data.audit_logs];
  const auditTable = document.querySelector('table tbody');
  
  if (auditTable) {
    auditTable.innerHTML = logs.map(log => `
      <tr>
        <td>${(() => {
          const time = log.time instanceof Date ? log.time : new Date(log.time);
          return `${time.toLocaleTimeString().slice(0, 5)} &bull; ${time.toLocaleDateString()}`;
        })()}</td>
        <td>${log.actor}</td>
        <td>${log.action}</td>
        <td>${log.target}</td>
        <td><span class="badge low">${log.result}</span></td>
      </tr>
    `).join('');
  }
}


function initCharts() {
  if (typeof Chart === 'undefined') return;

  if (currentPage === 'dashboard') {
    const activityCtx = document.getElementById('deviceActivityChart');
    if (activityCtx) {
      new Chart(activityCtx, {
        type: 'line',
        data: {
          labels: ['00:00', '04:00', '08:00', '12:00', '16:00', '20:00', '24:00'],
          datasets: [{
            label: 'Security events',
            data: [18, 24, 31, 42, 36, 52, 48],
            borderColor: '#5b87ff',
            backgroundColor: 'rgba(91, 135, 255, 0.16)',
            tension: 0.35,
            fill: true,
            pointRadius: 0,
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: { grid: { display: false }, ticks: { color: '#8e9fd6' } },
            y: { grid: { color: 'rgba(255,255,255,0.06)' }, ticks: { color: '#8e9fd6' } }
          }
        }
      });
    }

    const fraudCtx = document.getElementById('fraudSplitChart');
    if (fraudCtx) {
      new Chart(fraudCtx, {
        type: 'doughnut',
        data: {
          labels: ['Potential Fraud', 'Verified Alerts', 'Investigations'],
          datasets: [{
            data: [32, 18, 14],
            backgroundColor: ['#ff5d8f', '#73f3e8', '#d950ff'],
            hoverOffset: 6,
          }]
        },
        options: { responsive: true, plugins: { legend: { position: 'bottom', labels: { color: '#bec8f8' } } } }
      });
    }
  }

  if (currentPage === 'analytics') {
    const trendsCtx = document.getElementById('trendChart');
    if (trendsCtx) {
      const branches = dataManager.getBranches();
      new Chart(trendsCtx, {
        type: 'bar',
        data: {
          labels: branches.map(b => b.name),
          datasets: [{
            label: 'Alert volume',
            data: branches.map(b => b.alerts),
            backgroundColor: '#5b87ff',
            borderRadius: 20,
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: { grid: { display: false }, ticks: { color: '#b2bcff' } },
            y: { grid: { color: 'rgba(255,255,255,0.06)' }, ticks: { color: '#b2bcff' } }
          }
        }
      });
    }

    const riskCtx = document.getElementById('riskChart');
    if (riskCtx) {
      new Chart(riskCtx, {
        type: 'line',
        data: {
          labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul'],
          datasets: [{
            label: 'Risk exposure',
            data: [58, 52, 49, 61, 68, 74, 83],
            borderColor: '#73f3e8',
            backgroundColor: 'rgba(115, 243, 232, 0.16)',
            tension: 0.4,
            fill: true,
            pointRadius: 3,
          }]
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: { grid: { display: false }, ticks: { color: '#b2bcff' } },
            y: { grid: { color: 'rgba(255,255,255,0.06)' }, ticks: { color: '#b2bcff' } }
          }
        }
      });
    }
  }
}

function initNotifications() {
  const items = document.querySelectorAll('.alert-item');
  items.forEach((item, index) => {
    item.style.animation = `fadeUp 0.48s ease ${(index * 0.05)}s both`;
  });
}

function initLoginForm() {
  const form = document.querySelector('.login-form');
  if (!form) return;
  let selectedRole = window.SecguardAuth?.getRole() || 'company_admin';

  function enterRole(role) {
    if (window.SecguardAuth) SecguardAuth.setRole(role);
    try {
      localStorage.setItem('secguard_demo_session', 'true');
    } catch (error) {
      console.warn('Could not persist demo session flag.', error);
    }
    const route = window.SecguardSupabase?.routeForRole(role) || window.SecguardAuth?.routeForRole(role) || 'dashboard.html';
    window.location.href = route;
  }

  const roleSelect = document.querySelector('[data-role-select]');
  const params = new URLSearchParams(window.location.search);
  selectedRole = params.get('role') || selectedRole;
  if (window.SecguardAuth) SecguardAuth.setRole(selectedRole);
  if (roleSelect) {
    roleSelect.value = selectedRole;
    roleSelect.addEventListener('change', () => {
      selectedRole = roleSelect.value;
      if (window.SecguardAuth) SecguardAuth.setRole(selectedRole);
    });
  }

  form.addEventListener('submit', event => {
    event.preventDefault();
    const email = form.querySelector('input[type="email"]').value;
    const password = form.querySelector('input[type="password"]').value;
    if (!email || !password) {
      alert('Please provide email and password.');
      return;
    }
    if (window.SecguardSupabase) {
      window.SecguardSupabase.login(email, password, selectedRole).then(({ error, local }) => {
        if (error && !local) {
          console.warn('Supabase login failed. Entering local demo portal for testing.', error);
        }
        enterRole(selectedRole);
      });
      return;
    }
    enterRole(selectedRole);
  });

  const demoButton = document.querySelector('[data-demo-login]');
  if (demoButton) {
    demoButton.addEventListener('click', () => enterRole(selectedRole));
  }

  const signupButton = document.querySelector('[data-signup]');
  if (signupButton) {
    signupButton.addEventListener('click', () => {
      const email = form.querySelector('input[type="email"]').value;
      const password = form.querySelector('input[type="password"]').value;
      if (!email || !password) {
        alert('Enter email and password before signup.');
        return;
      }
      if (!window.SecguardSupabase) {
        alert('Supabase is not loaded.');
        return;
      }
      window.SecguardSupabase.signup(email, password, selectedRole).then(({ error }) => {
        if (error) {
          alert(error.message || 'Signup failed.');
          return;
        }
        alert('Signup request sent. Check email confirmation if Supabase requires it.');
      });
    });
  }

  const googleButton = document.querySelector('[data-google-login]');
  if (googleButton) {
    googleButton.addEventListener('click', () => {
      if (!window.SecguardSupabase) {
        alert('Supabase is not loaded.');
        return;
      }
      window.SecguardSupabase.googleLogin(selectedRole);
    });
  }
}

function initDeviceForm() {
  if (currentPage !== 'device-intelligence') return;
  const deviceForm = document.getElementById('device-input-form');
  const reviewButton = document.querySelector('.page-header .btn');
  if (reviewButton) {
    reviewButton.addEventListener('click', () => {
      deviceForm?.scrollIntoView({ behavior: 'smooth', block: 'center' });
      reviewButton.textContent = 'Queue ready';
      setTimeout(() => {
        reviewButton.textContent = 'Review device queue';
      }, 1400);
    });
  }
  if (!deviceForm) return;

  deviceForm.addEventListener('submit', event => {
    event.preventDefault();

    const imei = document.getElementById('imei-input').value.trim();
    const model = document.getElementById('model-input').value.trim();
    const status = document.getElementById('status-input').value.trim();
    const erpStatus = document.getElementById('erp-status-input').value.trim();
    const risk = document.getElementById('risk-input').value;

    if (!imei || !model || !status) {
      alert('Please complete all required fields.');
      return;
    }

    const riskScore = risk === 'high' ? 84 : risk === 'medium' ? 58 : 24;

    dataManager.addDevice({
      imei,
      model,
      activation_status: status,
      sim_changes: 0,
      last_sim_change: 0,
      erp_status: erpStatus,
      erp_sync_status: erpStatus === 'unsold' && status === 'active' ? 'desynced' : 'synced',
      risk_score: riskScore,
      branch: 'branch_alpha',
      last_seen: 'Just now',
      battery_health: 'Good',
      network_load: 'Normal',
      service_tier: 'Enterprise',
      active: true,
    }).then(() => {
      renderDeviceIntelligence();
      renderFraudDetection();
      renderDashboardAlerts();
      deviceForm.reset();
      alert('Device added. If it is active and unsold, Secguard generated a fraud alert.');
    });
  });
}

function initCustomerActions() {
  if (currentPage !== 'customer') return;
  const createButton = document.querySelector('.page-header .btn');
  const caseForm = document.getElementById('customer-case-form');
  if (caseForm) {
    caseForm.addEventListener('submit', event => {
      event.preventDefault();
      const formData = new FormData(caseForm);
      dataManager.createCustomerCase({
        customerName: formData.get('customerName'),
        phone: formData.get('phone'),
        imei: formData.get('imei'),
        model: formData.get('model'),
        reportType: formData.get('reportType'),
      });
      renderCustomerPortal();
      caseForm.reset();
      const status = document.querySelector('[data-customer-form-status]');
      if (status) status.textContent = 'Case saved. Open Live Tracking to see the reported phone in the tracking feed.';
    });
  }

  if (!createButton) return;

  createButton.addEventListener('click', () => {
    document.getElementById('customer-case-form')?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  });
}

function initActiveNav() {
  const links = document.querySelectorAll('nav a');
  links.forEach(link => {
    const href = link.getAttribute('href');
    if (href && location.pathname.endsWith(href)) {
      link.classList.add('active');
    }
  });
}

function getTrackingSignalStrength(score) {
  if (score >= 90) return 5;
  if (score >= 70) return 4;
  if (score >= 50) return 3;
  if (score >= 30) return 2;
  return 1;
}

function initTableSearch() {
  document.querySelectorAll('.table-wrapper').forEach((wrapper, index) => {
    const table = wrapper.querySelector('table');
    if (!table || wrapper.previousElementSibling?.classList?.contains('table-toolbar')) return;
    const toolbar = document.createElement('div');
    toolbar.className = 'table-toolbar';
    toolbar.innerHTML = `<input class="table-search" type="search" placeholder="Search table..." aria-label="Search table ${index + 1}">`;
    wrapper.parentElement.insertBefore(toolbar, wrapper);
    const input = toolbar.querySelector('input');
    input.addEventListener('input', () => {
      const query = input.value.trim().toLowerCase();
      table.querySelectorAll('tbody tr').forEach(row => {
        row.hidden = query && !row.textContent.toLowerCase().includes(query);
      });
    });
  });
}

function getDeviceCoordinates(device, index) {
  const base = [
    [-1.286389, 36.817223],
    [-1.265, 36.804],
    [-1.303, 36.826],
    [-1.292, 36.78],
    [-1.25, 36.89],
  ];
  const point = base[index % base.length];
  const jitter = (Number(device.risk_score || 0) % 9) / 1000;
  return [point[0] + jitter, point[1] - jitter];
}

function renderTrackingMap(devices) {
  const mapNode = document.getElementById('tracking-map');
  if (!mapNode || typeof L === 'undefined') return;
  const fallbackCenter = [-1.286389, 36.817223];
  if (!state.trackingMap) {
    state.trackingMap = L.map(mapNode, { zoomControl: true }).setView(fallbackCenter, 12);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: '&copy; OpenStreetMap',
    }).addTo(state.trackingMap);
    setTimeout(() => state.trackingMap.invalidateSize(), 80);
  }

  state.trackingMarkers.forEach(marker => marker.remove());
  state.trackingMarkers = devices.map((device, index) => {
    const coords = getDeviceCoordinates(device, index);
    return L.marker(coords)
      .addTo(state.trackingMap)
      .bindPopup(`<strong>${device.model}</strong><br>${dataManager.formatIMEI(device.imei)}<br>${device.routeStatus}`);
  });

  if (state.trackingMarkers.length) {
    const bounds = L.latLngBounds(state.trackingMarkers.map(marker => marker.getLatLng()));
    state.trackingMap.fitBounds(bounds, { padding: [28, 28], maxZoom: 14 });
  }
}

function renderTrackingPage() {
  if (currentPage !== 'tracking') return;
  
  const trackingKpiGrid = document.getElementById('tracking-kpi-grid');
  const deviceList = document.querySelector('.device-list');
  const trackingTableBody = document.getElementById('tracking-table-body');

  const devices = getVisibleDevices().map(device => {
    const signalStrength = getTrackingSignalStrength(device.risk_score);
    const routeStatus = device.erp_sync_status !== 'synced'
      ? 'ERP mismatch'
      : device.risk_score > 80
      ? 'Off route'
      : 'On route';

    return {
      ...device,
      signalStrength,
      signalLabel: `${signalStrength}/5 bars`,
      lastSeenLabel: dataManager.formatDate(device.timestamp),
      routeStatus,
    };
  });

  const liveDevices = devices.filter(device => device.activation_status === 'active');
  const desyncedDevices = devices.filter(device => device.erp_sync_status !== 'synced');
  const offRouteDevices = devices.filter(device => device.routeStatus !== 'On route');
  const averageSignal = devices.length
    ? Math.round(devices.reduce((sum, device) => sum + device.signalStrength, 0) / devices.length)
    : 0;

  renderTrackingMap(devices);

  if (trackingKpiGrid) {
    const kpis = [
      {
        label: 'Live devices',
        value: liveDevices.length,
        trend: 'Real-time',
        class: 'low',
      },
      {
        label: 'ERP desyncs',
        value: desyncedDevices.length,
        trend: 'Action',
        class: desyncedDevices.length > 0 ? 'high' : 'low',
      },
      {
        label: 'Off-route alerts',
        value: offRouteDevices.length,
        trend: 'Monitoring',
        class: offRouteDevices.length > 0 ? 'high' : 'low',
      },
      {
        label: 'Avg signal',
        value: `${averageSignal}/5`,
        trend: 'Healthy',
        class: averageSignal > 3 ? 'low' : 'medium',
      },
    ];
    
    trackingKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Live tracking performance metric for the field feed.</p>
      </article>
    `).join('');
  }

  if (deviceList) {
    const topDevices = devices
      .sort((a, b) => b.timestamp - a.timestamp)
      .slice(0, 3);

    deviceList.innerHTML = topDevices.length ? topDevices.map(device => `
      <div class="device-card">
        <div class="status-pill ${device.routeStatus === 'On route' ? 'low' : device.routeStatus === 'ERP mismatch' ? 'high' : 'medium'}">
          <span></span>${dataManager.formatIMEI(device.imei)}
        </div>
        <div><strong>${device.model}</strong></div>
        <p>Last online: ${device.lastSeenLabel} &bull; Signal: ${device.signalStrength} bars &bull; ${device.routeStatus}</p>
      </div>
    `).join('') : '<div class="activity-item"><strong>No tracking record yet</strong><span>Register or report a phone from My Protection first.</span></div>';
  }

  const mapSummary = document.getElementById('tracking-map-summary');
  if (mapSummary) {
    mapSummary.innerHTML = `${liveDevices.length} live devices &bull; ${desyncedDevices.length} ERP desyncs &bull; ${offRouteDevices.length} off-route alerts`; 
  }

  const trackingOffRoutePill = document.getElementById('tracking-offroute-pill');
  if (trackingOffRoutePill) {
    trackingOffRoutePill.innerHTML = `<strong>${offRouteDevices.length}</strong> devices off-route`;
  }

  if (trackingTableBody) {
    trackingTableBody.innerHTML = devices.length ? devices.map(device => `
      <tr>
        <td>${dataManager.formatIMEI(device.imei)}<br><small>${device.model}</small></td>
        <td>${device.lastSeenLabel}</td>
        <td>${device.routeStatus}</td>
        <td>${device.signalLabel}</td>
        <td>${device.erp_sync_status}</td>
      </tr>
    `).join('') : '<tr><td colspan="5">No tracked phone yet. Register or report one from My Protection.</td></tr>';
  }
}

function initTrackingRefresh() {
  if (currentPage !== 'tracking') return;
  const refreshBtn = document.querySelector('.page-header .btn');
  if (!refreshBtn) return;

  refreshBtn.addEventListener('click', () => {
    renderTrackingPage();
    refreshBtn.textContent = 'Feed refreshed';
    setTimeout(() => {
      refreshBtn.textContent = 'Refresh feed';
    }, 1200);
  });
}

function initDashboardActions() {
  if (currentPage !== 'dashboard') return;
  const buttons = Array.from(document.querySelectorAll('.top-actions .btn'));
  const exportButton = buttons.find(button => button.textContent.trim().toLowerCase().includes('export'));
  const resolveButton = buttons.find(button => button.textContent.trim().toLowerCase().includes('resolve'));

  if (exportButton) {
    exportButton.addEventListener('click', () => {
      const snapshot = dataManager.exportSnapshot();
      const blob = new Blob([snapshot], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `secguard-report-${Date.now()}.json`;
      link.click();
      URL.revokeObjectURL(url);
      exportButton.textContent = 'Report exported';
      renderAuditLogs();
      setTimeout(() => {
        exportButton.textContent = 'Export report';
      }, 1400);
    });
  }

  if (resolveButton) {
    resolveButton.addEventListener('click', () => {
      const resolved = dataManager.resolveOpenAlerts();
      renderAllPages();
      resolveButton.textContent = `${resolved} reviewed`;
      setTimeout(() => {
        resolveButton.textContent = 'Resolve alerts';
      }, 1400);
    });
  }
}

function initFraudActions() {
  if (currentPage !== 'fraud') return;
  const incidentButton = document.querySelector('.page-header .btn');
  if (!incidentButton) return;
  incidentButton.addEventListener('click', () => {
    const openAlerts = dataManager.getFraudAlerts({ status: 'open' }).length;
    dataManager.addAudit('Opened incident board', `${openAlerts} open alert(s)`);
    renderFraudDetection();
    incidentButton.textContent = `${openAlerts} incidents loaded`;
    setTimeout(() => {
      incidentButton.textContent = 'Open incident board';
    }, 1400);
  });
}

function renderSettingsPage() {
  if (currentPage !== 'settings') return;
  const settings = dataManager.getSettings();
  const fields = {
    workspace: document.getElementById('workspace'),
    timezone: document.getElementById('timezone'),
    notify: document.getElementById('notify'),
    mfa: document.getElementById('mfa'),
    risk: document.getElementById('risk'),
    erpLink: document.getElementById('erp-link'),
    adminNotes: document.getElementById('admin-notes'),
  };

  Object.entries(fields).forEach(([key, field]) => {
    if (field && settings[key] !== undefined) field.value = settings[key];
  });
}

function initSettingsActions() {
  if (currentPage !== 'settings') return;
  const saveButton = document.querySelector('.page-header .btn');
  if (!saveButton) return;

  saveButton.addEventListener('click', () => {
    dataManager.saveSettings({
      workspace: document.getElementById('workspace')?.value || '',
      timezone: document.getElementById('timezone')?.value || '',
      notify: document.getElementById('notify')?.value || '',
      mfa: document.getElementById('mfa')?.value || '',
      risk: document.getElementById('risk')?.value || '',
      erpLink: document.getElementById('erp-link')?.value || '',
      adminNotes: document.getElementById('admin-notes')?.value || '',
    });
    saveButton.textContent = 'Configuration saved';
    setTimeout(() => {
      saveButton.textContent = 'Save configuration';
    }, 1400);
  });
}

function renderAnalyticsPage() {
  if (currentPage !== 'analytics') return;
  
  const analyticsKpiGrid = document.querySelector('.kpi-grid');
  
  if (analyticsKpiGrid) {
    const devices = dataManager.getDevices();
    const metrics = dataManager.getDashboardMetrics();
    const averageRisk = devices.length
      ? Math.round(devices.reduce((sum, device) => sum + Number(device.risk_score || 0), 0) / devices.length)
      : 0;
    const branchAnomalies = dataManager.getBranches().filter(branch => Number(branch.alerts || 0) > 10).length;
    const kpis = [
      { label: 'Alert coverage', value: `${metrics.fraudAlerts}`, trend: 'Open alerts', class: metrics.fraudAlerts ? 'high' : 'low' },
      { label: 'Risk index', value: averageRisk, trend: averageRisk > 60 ? 'High' : 'Managed', class: averageRisk > 60 ? 'high' : 'medium' },
      { label: 'Branch anomalies', value: branchAnomalies, trend: branchAnomalies ? 'Elevated' : 'Clear', class: branchAnomalies ? 'high' : 'low' },
      { label: 'Open investigations', value: metrics.openInvestigations, trend: 'Active', class: metrics.openInvestigations ? 'medium' : 'low' },
    ];
    
    analyticsKpiGrid.innerHTML = kpis.map(kpi => `
      <article class="card kpi-card">
        <div class="metric">
          <div>
            <small>${kpi.label}</small>
            <div class="value">${kpi.value}</div>
          </div>
          <span class="badge ${kpi.class}">${kpi.trend}</span>
        </div>
        <p>Analytics metric for operational insight.</p>
      </article>
    `).join('');
  }
}

function initAnalyticsActions() {
  if (currentPage !== 'analytics') return;
  const exportButton = document.querySelector('.page-header .btn');
  if (!exportButton) return;

  exportButton.addEventListener('click', () => {
    const snapshot = dataManager.exportSnapshot();
    const blob = new Blob([snapshot], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `secguard-analytics-${Date.now()}.json`;
    link.click();
    URL.revokeObjectURL(url);
    exportButton.textContent = 'Insights exported';
    setTimeout(() => {
      exportButton.textContent = 'Export insights';
    }, 1400);
  });
}

async function initPage() {
  try {
    initSidebarToggle();
    initLoginForm();

    if (!enforceRoleAccess()) return;
    applyRoleNavigation();

    if (typeof dataManager === 'undefined') return;

    await dataManager.load();
    if (!dataManager.storageAvailable) showToast('Storage is unavailable. Running in memory-only demo mode.');

    initCharts();
    initNotifications();
    initDeviceForm();
    initTrackingRefresh();
    initDashboardActions();
    initFraudActions();
    initCustomerActions();
    initSettingsActions();
    initAnalyticsActions();
    initActiveNav();
    initTableSearch();

    renderDashboardKPIs();
    renderDashboardBranches();
    renderDashboardAlerts();
    renderDeviceIntelligence();
    renderFraudDetection();
    renderCustomerPortal();
    renderAuditLogs();
    renderAnalyticsPage();
    renderTrackingPage();
    renderSettingsPage();

    startLiveSimulation();
  } catch (error) {
    showFatalError(error);
  }
}

window.addEventListener('DOMContentLoaded', initPage);
